# Generated by Django 3.2.6 on 2021-08-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('lastdonateddate', models.DateField(default='', max_length=50)),
            ],
        ),
    ]
