# Generated by Django 3.2.6 on 2021-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
                ('mobile_num', models.BigIntegerField()),
                ('last_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
