# Generated by Django 3.2.6 on 2021-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='last_donated_date',
            field=models.CharField(max_length=50),
        ),
    ]
