# Generated by Django 3.2.6 on 2021-08-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pname',
            new_name='pname',
        ),
    ]
