# Generated by Django 3.2.6 on 2021-08-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldgrp', models.CharField(default='', max_length=50)),
                ('donorname', models.CharField(default='', max_length=50)),
                ('donoradd', models.CharField(default='', max_length=50)),
                ('pincode', models.IntegerField(default='')),
                ('mobile', models.BigIntegerField(default='')),
                ('lastblddonate', models.DateField(default='')),
            ],
        ),
    ]
