# Generated by Django 3.2.6 on 2021-08-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('bloodg', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('mobile', models.BigIntegerField()),
                ('lastdonate', models.DateField()),
            ],
        ),
    ]
