# Generated by Django 3.2.6 on 2021-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('bloodgroup', models.CharField(max_length=50)),
                ('mobileno', models.BigIntegerField()),
                ('lastdonateddate', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(max_length=50)),
            ],
        ),
    ]
